version: "3.6"
x-env: &defaults
  NODE_ENV: development
  NODE_PATH:
services:
  web:
    stdin_open: true
    container_name: gatsby-docs
    image: gatsby-docs:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /opt/app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 128000000
      - ./static/environment.js:/usr/share/nginx/html/config.js
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      <<: *defaults
    command: >
      bash -c "gatsby develop"
